version: '3.4'
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: luizimcpi/ktor-rinha-mongo-service
    environment:
      - MONGO_URL=mongodb://root:root@localhost
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
